export const COUNTRIES = [
  { code: "TH", label: "ไทย (Thailand)" },
  { code: "JP", label: "ญี่ปุ่น (Japan)" },
  { code: "KR", label: "เกาหลีใต้ (South Korea)" },
  { code: "CN", label: "จีน (China)" },
  { code: "VN", label: "เวียดนาม (Vietnam)" },
  { code: "ID", label: "อินโดนีเซีย (Indonesia)" },
  { code: "MY", label: "มาเลเซีย (Malaysia)" },
  { code: "PH", label: "ฟิลิปปินส์ (Philippines)" },
  { code: "SG", label: "สิงคโปร์ (Singapore)" },
  { code: "LA", label: "ลาว (Laos)" },
  { code: "MM", label: "เมียนมา (Myanmar)" },
  { code: "KH", label: "กัมพูชา (Cambodia)" },
  { code: "US", label: "สหรัฐอเมริกา (United States)" },
  { code: "GB", label: "สหราชอาณาจักร (United Kingdom)" },
  { code: "FR", label: "ฝรั่งเศส (France)" },
  { code: "DE", label: "เยอรมนี (Germany)" },
  { code: "ES", label: "สเปน (Spain)" },
  { code: "IT", label: "อิตาลี (Italy)" },
  { code: "RU", label: "รัสเซีย (Russia)" },
  { code: "CA", label: "แคนาดา (Canada)" },
  { code: "AU", label: "ออสเตรเลีย (Australia)" },
  { code: "NZ", label: "นิวซีแลนด์ (New Zealand)" },
  { code: "BR", label: "บราซิล (Brazil)" },
  { code: "IN", label: "อินเดีย (India)" },
  { code: "TW", label: "ไต้หวัน (Taiwan)" },
  { code: "HK", label: "ฮ่องกง (Hong Kong)" },
].sort((a, b) => a.label.localeCompare(b.label, "th"));
